import os
from supabase import create_client
import pytz

# Environment Variables
BOT_TOKEN = os.getenv("BOT_TOKEN")
SUPABASE_URL = os.getenv("SUPABASE_URL")
SUPABASE_KEY = os.getenv("SUPABASE_KEY")
WEBHOOK_URL = os.getenv("WEBHOOK_URL")
WEBHOOK_PATH = "/webhook"
PORT = int(os.getenv("PORT", 8080))

# Supabase Client
supabase = create_client(SUPABASE_URL, SUPABASE_KEY)
IST = pytz.timezone("Asia/Kolkata")

# States
CATEGORY, AMOUNT, WALLET, NOTE, DATE = range(5)
UPDATE_ID, UPDATE_DATA, UPDATE_CONFIRM = range(20, 23)
DELETE_ID, DELETE_CONFIRM = range(30, 32)
BUDGET_MENU = 1000
BUDGET_WALLET = 1101
BUDGET_CATEGORY = 1102
BUDGET_AMOUNT = 1103
BUDGET_DEFAULT = 1104
BUDGET_START_DATE = 1200
BUDGET_END_DATE = 1201
BUDGET_VIEW_CHOICE = 1100
DELETE_BUDGET_ID, DELETE_BUDGET_CONFIRM = range(1105, 1107)
